// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/**
    Platform  Firebase App Id
    android   1:673062991187:android:254bf382a8132282201da6
    ios       1:673062991187:ios:fd7b02cc7ec1413a201da6
 */

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmO-7UE8aaxNzkbkehyAQDycpFDbmolc',
    appId: '1:673062991187:android:254bf382a8132282201da6',
    messagingSenderId: '673062991187',
    projectId: 'marvalfit-d2a98',
    storageBucket: 'marvalfit-d2a98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA1zPwDG8X5mUSw1hdwXq_fOGzEoNZrcA',
    appId: '1:673062991187:ios:fd7b02cc7ec1413a201da6',
    messagingSenderId: '673062991187',
    projectId: 'marvalfit-d2a98',
    storageBucket: 'marvalfit-d2a98.appspot.com',
    iosClientId: '673062991187-9tohh9t28ndvk3uf23cjn9g3vgee3k21.apps.googleusercontent.com',
    iosBundleId: 'com.zgz.vlandiblas.marvalfit',
  );
}
